---
controller_execution_environments:
  - name: legacy workshop execution environment
    image: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest
  - name: ripu workshop execution environment
    image: registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9:latest
...
