---
controller_inventories:
  - name: Workshop Inventory
    organization: Default

  - name: Demo Inventory
    organization: Default
    state: absent
controller_groups:
  - name: ALL_rhel
    inventory: Workshop Inventory
    description: All RHEL hosts in the workshop
    hosts:
      - node1
      - node2
      - node3

  - name: rhel7
    inventory: Workshop Inventory
    description: RHEL 7 hosts in the workshop
    hosts:
      - node1

  - name: rhel8
    inventory: Workshop Inventory
    description: RHEL 8 hosts in the workshop
    hosts:
      - node2

  - name: rhel9
    inventory: Workshop Inventory
    description: RHEL 9 hosts in the workshop
    hosts:
      - node3
...
