---
- name: Wait for connection...
  ansible.builtin.wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: Add a remote root login with password that will cause a RHEL 8 inhibitor
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - {key: "PermitRootLogin", value: "yes"}
    - {key: "PasswordAuthentication", value: "yes"}
  notify:
    - Restart sshd
  when: ansible_distribution_major_version|int == 8